### ISSUE TITLE
Optional Whale Cap on vote size

### ISSUE THREAD

**Issue by JakeHartnell** [JakeHartnell/cw-dao#2]
Token based voting is great, but the downside is that whales can completely dominate some communities.

Would be great to potentially integrate an optional "whale cap" parameter. In other words the _max vote size_.

Ideally, whale sized votes would sill count towards quorum.

**Comment by ebaker** [comment]
- Add wale cap `Option` on config.
 - Extend config and fix unit tests
- When voting, check wale cap in config.
 - Write unit test for wale cap

**Comment by PotasticPotatoe** [comment]
Problems with this:

In the extreme users are limited to 1 vote. This would cause our current total weight consensus to be stuck in an OpenProposal state. A solution would be to see the current number of addresses of the CW token, and use the whale limit to set a target weight that needs to be passed. This logic is very hacky and would need to be calibrated for both quorums. This is because we'd have to have logic that tests up to an infinity number of addresses (and even then there would exist edge cases that result in a stuck state).

Another way could be to test this configuration at instantiation by making sure the whale limit is set at a valid state at instantiation (could be done by seeing how many current holders we have). However, each individual token holder holds different amounts and we'd need to query all of them to get the amount of tokens they have. Afterward, get either the minimum of the whale limit or tokens the user have. Finally make sure that the target weight can be met given 51% of those hit the target. One problem here is that individuals can manually change the whale limit, we would have to disable this behavior. Again, here we could just add this logic to the proposal instead of the config. 

Wale Cap Avoidance:
A wale could still circumvented this logic generating N addresses, sending each one some tokens and then voting on a contract to get a proposal through.

**Comment by JakeHartnell** [comment]
All valid points. Thanks so much for the thoughtful response. :pray: 

> Another way could be to test this configuration at instantiation by making sure the whale limit is set at a valid state at instantiation (could be done by seeing how many current holders we have). However, each individual token holder holds different amounts and we'd need to query all of them to get the amount of tokens they have. Afterward, get either the minimum of the whale limit or tokens the user have. Finally make sure that the target weight can be met given 51% of those hit the target. One problem here is that individuals can manually change the whale limit, we would have to disable this behavior. We would add a snapshot of the whale limit to the proposal from the config (to prevent overwriting).

This could be drastically complicate the code base, and would do nothing to address sybil attacks as you mentioned, so I think it's best to close this. In hindsight, not my best idea. :joy:
